export const Blogs = [
    {
        id: 101,
        title: "14 Killed As Suspected Herdsmen Attack Benue Community",
        author: "Pius Angbo",
        time: "September 22, 2022",
        image: "https://www.channelstv.com/wp-content/uploads/2021/04/Gunmen-Benue.jpg",
        description: "Suspected herdsmen have killed 14 people in a fresh attack on the Mchia community in Logo Local Government Area of Benue State.",
        body: "Mchia is a settlement between Abeda and Anyiin, located on Ugba-Anyiin road, Logo local government area in the north-central state. The Special Adviser to the Governor on Security Matters, Colonel Paul Hamba(retired) confirmed this to journalists after a Security Council meeting in Makurdi, the state capital. He said the attack occurred on Wednesday night while the herdsmen, fully armed, stormed the community around 9 pm. Meanwhile, troops of Operation Whirl Stroke have thwarted an attack on the Ortese Internally Displaced Persons (IDP) camp in the Guma Local Government Area of the state. Commander of Operation Whirl Stroke, Major General Kevin Aligbe, disclosed this to Channels Television in an interview, saying the troops killed the herdsmen in the counter- offensive operation. According to the Commander, a soldier who was involved in the operation slumped and died at the hospital. 'We got information about these people(terrorists) planning to attack Ortese, Nkohol and two other locations in Guma LGA on Tuesday night; and we quickly deployed that night and reinforced the places yesterday morning,' he said. 'My troops noticed where those guys were hibernating in the bush and went after them.Of course, they made contact with them.They saw them carrying their casualties and running into the bush.Coming back, one of our soldiers just slumped, he was not shot'. 'He was rushed to the hospital where he was confirmed dead.We are still maintaining the trend in that axis and that is why you have not heard about any attack.We were still in Human when we heard about the Logo attack.'The pattern of settlement of the people too is not helping us.But our troops are managing the situation in Logo.Some things had been happening around that area before now which made us conduct a weeklong operation there about two weeks ago.Even my Sector Commander had to move to the area.'If you notice, these terrorists have killed between the to four people every three to four days.So, we needed to just clear that side.Before you know it, you will just hear that they have attacked and run away.The pattern of settlement is not also helping matters too.They go to isolated areas where they know that security is not near and they kill innocent farmers and other innocent people.'",
        source: "https://www.channelstv.com/2022/09/22/14-killed-as-suspected-herdsmen-attack-benue-community/"
    },
    {
        id: 102,
        title: "‘So Much Concentration On The Centre’: Gov Emmanuel Seeks Review Of Exclusive List",
        author: "Kayode Oyero",
        time: "September 22, 2022",
        image: "https://i.ytimg.com/vi/45rORcmbJyk/hqdefault.jpg",
        description: "Governor Udom Emmanuel of Akwa Ibom State says there is a need to review the Exclusive Legislative List to give states more control over critical areas.",
        body: '“I think we need to look back into what we call Exclusive List. There is so much concentration on the centre and renders the states not being able to operate very well. I’m serious about this and if we can be sincere, and leave politics aside, there is so much we can allow states to do so that those who are willing can go ahead and do them,” Emmanuel said on Channels Television’s Sunrise Daily programme on Thursday. The governor spoke in Uyo, the state capital, amid celebrations to mark the 35th anniversary of the creation of the state. At the moment, the Federal Government has control over 68 items in the Exclusive List such as aviation, currency, security, and customs, amongst others, whilst the Concurrent Legislative List provides for items both the government at the centre and state governments share control over.They include allocation of revenue; a collection of taxes; industrial, commercial, or agricultural development; amongst others. The governor said the constitution must be looked at for states to work, like other federating units overseas. “I like reading about the economies of states and countries that are successful.During COVID, I was reading somewhere about New York and they were feeling so bad that the revenue they were getting during COVID dropped to over $16bn.I said my God, this is just a state.So, what makes them make that kind of revenue ? “I know we have a completely different economy but what principle gave rise to that(revenue) ?” he asked. “I still believe, in an economic eye, we need to look at certain things that are in our constitution which we can as well decentralise to make states work.I’ve talked about the Exclusive List. “Something like this is a national issue and you don’t go to the minutest details because the understanding of everybody might not be the same. I try not to say all. A lot of these I keep promising Nigerians that PDP (Peoples Democratic Party) will look into it when we come in,” Emmanuel further stated. “If we look at that, it will help states a whole lot to develop.Take, for example, power.Today, I cannot do anything on this shoreline, I must go back to NPA.There are no decisions I can take.For me to even bring a new aircraft, a whole lot of bottlenecks.I don’t even want to go into that.We are making it so difficult to do business.The Ease of Doing Business is not easy.',
        source: "https://www.channelstv.com/2022/09/22/so-much-concentration-on-the-centre-gov-emmanuel-seeks-review-of-exclusive-list/"
    },
    {
        id: 103,
        title: "Paris Club Refund: Court Sets Aside Consent Judgement On Payment Of $47m",
        author: "Emmanuella Obaje-Daniels",
        time: "September 22, 2022",
        image: "https://www.channelstv.com/wp-content/uploads/2020/01/Federal-High-Court-Abuja1.jpg",
        description: "The Chief Judge of the Federal High Court Abuja, Justice John Tsoho,  has set aside a consent judgement in favour of Panic Alert Security Systems Limited against the Nigeria Governors’ Forum (NGF).",
        body: 'Delivering the ruling on Wednesday, Justice Tsoho, held that the said consent judgement was entered without jurisdiction in its entirety.The company is one of the beneficiaries of the payment of $418 million to consultants and is said to be for payment for professional services in the Paris Club refund to State Governments.It had relied on the consent judgement to lay claim to professional fees of over $40 million.Earlier, the court had restricted the Federal Government from deducting $418 million from the bank accounts of the 36 states. The state governors had accused the Attorney- general of the Federation(AGF), Abubakar Malami, of alleged involvement in the controversial payment. The Governors’ Forum later instructed its counsel, Senior Advocate of Nigeria, Paul Ogbole, to challenge the consent judgment the AGF relied upon in court. Justice Tsoho agreed with counsel to the NGF that the reliefs claimed by the company were premised on a simple contract which by section 251 of the Constitution of the Federal Republic of Nigeria 1999(as amended) strips the court ab initio the required jurisdiction to entertain such matters. Accordingly, the court set aside the consent judgement. By the ruling, all approvals by the AGF, the president, the minister of finance, the Accountant - General of the Federation and the Debt Management Office(DMO) arising from, related to, or concerning Panic Alert’s claims have been voided.',
        source: "https://www.channelstv.com/2022/09/22/paris-club-refund-court-sets-aside-consent-judgement-on-payment-of-47m/"
    },
    {
        id: 104,
        title: "Why Nigeria Needs More Women In Leadership Roles Within Government – Osinbajo",
        author: "Channels Television ",
        time: "September 22, 2022",
        image: "https://www.channelstv.com/wp-content/uploads/2022/01/african-union-osinbajo.jpg",
        description: "Vice President Yemi Osinbajo, SAN, has is of the opinion that like the example of the education of the girl-child, a more effective and balanced female representation and participation in politics and government will have major impact on the country’s socio-economic future and overall national development.",
        body: 'Prof. Osinbajo stated this today as the Special Guest of Honour at the 2022 Women Directors’ Conference. Speaking in a pre- recorded message on the theme of the Conference: Facing Forward – The Evolving Nature of Boards in a Rapidly Changing World, the Vice President advocated for more female representation in leadership positions in government and across different sectors, “as an economic imperative and not a moral duty of men or mere concession by men.” Said he, “a country that keeps down half of its productive demography is bound to perform sub - optimally.But the issue is not just board representation, it is about representation in politics and government this is where major decisions affecting our lives are made.But perhaps, most importantly, it is about education of girls. “The high levels of female illiteracy is dangerous from all possible standpoints.If half your population is uneducated, it means that development and being competitive in a knowledge - driven world will not happen or will happen too slowly to be of much use.”',
        source: "https://www.channelstv.com/2022/09/22/why-nigeria-needs-more-women-in-leadership-roles-within-government-osinbajo/"
    },
    {
        id: 105,
        title: "Amanpour Says Iran President Interview Scrapped Over Headscarf Demand",
        author: "Channels Television",
        time: "September 22, 2022",
        image: "https://www.channelstv.com/wp-content/uploads/2022/09/Veteran-journalist-Christiane-Amanpour-cnn.jpg",
        description: "Veteran journalist Christiane Amanpour said Thursday that an interview with Iranian President Ebrahim Raisi was scrapped after he insisted she wear a headscarf, the focus of major protests in the cleric-run state.",
        body: 'Amanpour, the chief international anchor of CNN who also has a show on US public broadcaster PBS, said she was ready for the interview Wednesday on the sidelines of the UN General Assembly when an aide insisted she cover her hair. “I politely declined.We are in New York, where there is no law or tradition regarding headscarves,” Amanpour, who was born in Britain to an Iranian father, wrote on Twitter.“I pointed out that no previous Iranian president has required this when I have interviewed them outside Iran,” she said. “I said that I couldn’t agree to this unprecedented and unexpected condition.” She posted a picture of herself — without a headscarf — sitting in front of an empty chair where Raisi would have been. An aide to Raisi, a hardline cleric, told Amanpour that he was insisting on a headscarf because of “the situation in Iran,” she said. Iran has been swept by nearly a week of protests since the death of 22 - year - old Mahsa Amini, who died after being arrested by morality police that enforce the clerics’ rules on how women dress. A non - governmental group said that at least 31 Iranian civilians have been killed in the crackdown on the protests, in which women have been seen burning headscarves.',
        source: "https://www.channelstv.com/2022/09/22/amanpour-says-iran-president-interview-scrapped-over-headscarf-demand/"
    },
    {
        id: 106,
        title: "PDP Crisis: Wike Promises To Not Leave Party",
        author: "Joshua Rogers",
        time: "September 22, 2022",
        image: "https://www.channelstv.com/wp-content/uploads/2022/05/Nyesom-Wike.jpg",
        description: "Rivers State Governor Nyesom Wike says contrary to some expectations, he and his loyalists in Rivers State will not leave the Peoples Democratic Party (PDP) but remain to continue the fight for internal democracy.",
        body: 'Governor Wike stated this during a meeting with stakeholders of the party across the 319 wards of the state at the Banquet Hall of the Government House in Port Harcourt on Thursday. He said retreating from a fight is a sign of weakness.The meeting was to brief the party leaders on the recent happenings in the party and intimate them of the plan by the Governor to hold a media chat tomorrow at 10 am to speak on the state of the PDP in the country. Wike said the planned media chat is to publish his side of the story, which he maintained is the truth, and expose the ill characters of some persons who pride themselves as national leaders.According to him, after the chat, it will be left for Nigerians to decide if such people are still worthy of the ovation they are accorded. Governor Wike wondered why the PDP which is promising to unify Nigeria, cannot unite the party. Governor Wike says despite the internal crisis at the national level and a pocket of antagonism by some ungrateful PDP members in Rivers State, the party will retain all elective positions in the state.The PDP is currently occupying all three senatorial seats, 13 House of Representatives positions, 32 state House of Assembly seats, 23 Council chairmanship and 319 councilorship positions. Wike, a former minister, boasted of being well ahead of his detractors, saying he gets wind of every plan before it is executed. He also warned party members in the state against acting as moles because there will be no loopholes in the strategy that will be adopted by the party in the state for the 2023 elections. Meanwhile, the Chairman of the PDP in Rivers State, Ambassador Desmond Akawor, says members of the party in the State are committed to supporting the political ideals of Governor Wike and will obey his instructions on the next line of actions ahead of the elections. Akawor, a former Nigerian Ambassador to South - Korea, says the party is pleased with the way Governor Wike has been running the state both in administration and politics.',
        source: "https://www.channelstv.com/2022/09/22/pdp-crisis-wike-promises-to-not-leave-party-but-fight-for-democracy/"
    },
    {
        id: 107,
        title: "Manchester United Report £115.5m Loss For 2021/22 Season",
        author: "Channels Television",
        time: "September 22, 2022",
        image: "https://www.channelstv.com/wp-content/uploads/2022/05/Untitled-1-Recovered-Recovered-5.png",
        description: "Manchester United on Thursday announced a net loss of £115.5 million ($130.4 million, 132.2 million euros) for the 2021/22 season even though revenues rose to £583 million as coronavirus restrictions eased.",
        body: 'The financial year to June 30, 2022 also brought a 22 per cent rise in debt and a 19 per cent increase in wages. The 20-time English champions’ net debt increased from £419.5 million in 2021 to £514.9 million. United attributed the rise in debt mainly to the fall of the pound which increased the value of US dollar borrowings. Among other large items were dividends of £33.6 million to shareholders and the £24.7 million compensation package for former manager Ole Gunnar Solskjaer, sacked in November 2021. The biggest contributor to United’s spiralling costs was the increase in wages to £384.2 million. The return of Cristiano Ronaldo to Old Trafford, allied to summer signings of Raphael Varane and Jadon Sancho had United fans dreaming of a Premier League title challenge a year ago. Instead, they finished sixth, with their lowest points total of the Premier League era. The failure to qualify for the Champions League will hit United’s finances for this season. The club still heavily backed new manager Erik ten Hag in the summer, spending over £200 million on Antony, Casemiro, Lisandro Martinez and Tyrell Malacia. “Our club’s core mission is to win football matches and entertain our fans,” said United CEO Richard Arnold. “Since our last earnings report, we have strengthened our men’s first team squad, completed a successful summer tour, and established a foundation to build from in the early stages of the 2022 / 23 season under our new manager.” After a disastrous start to Ten Hag’s reign with defeats to Brighton and Brentford, United have won their last four Premier League games to climb to fifth in the table, six points behind early season leaders Arsenal but with a game in hand.',
        source: "https://www.channelstv.com/2022/09/22/manchester-united-report-115-5m-loss-for-2021-22-season/"
    },
    {
        id: 108,
        title: "Mob Attacks Journalist Covering Jigawa Flooding",
        author: "Sadiq Ilyas",
        time: "September 22, 2022",
        image: "https://www.channelstv.com/wp-content/uploads/2022/08/Jigawa-Flood.jpg",
        description: "A mob attacked a reporter with Manhaja newspaper, Abubakar Tahir, while he was covering the devastating flood in Ganuwar Kuka village, in Hadejia local government area of Jigawa State, northwest Nigeria.",
        body: 'The Police Public Relations Officer in the State DSP Lawal Shiisu confirmed this to Channels Television on Thursday, saying the mob almost drowned the journalist who was trying to report the flood devastation in the area. According to him, it took the intervention of some good samaritans in the area that Mr Abubakar was saved from being lynched by the angry youth in the village. “We have received a report of an attack on a journalist in the Hadejia area where they are currently ravaged by a devastating flood.A mob attacked him, destroyed his mobile phones, and tried to drown him in the water,” DSP Shiisu said. DSP Shiisu however, advised journalists against reaching out to traditional rulers of communities before they start working especially in the Hadejia area as they have a history of attacking journalists during times like this. The police spokesman stated that after reaching the flood - affected area, the journalist presented his identification card and began an interview with some of the victims, but unfortunately, some people began hitting him from behind. “As I stood up to ask why they were beating me, they forced my head down in the water and tried to drown me and continue to hit me when someone brought out a knife then some people now stopped them. “They now took me to the district head house where he gave me new clothes to wear and ask a bike man to take me to Hadejia General hospital for treatment,” the spokesman added. The people of the town are said to be angry with the government for inaction as perennial floods continue to wreak havoc year in and year out in their communities. In 2019, the Special Advisor to the governor on Community, and Social Inclusion, an indigene of Hadejia, Hamza Muhammad, narrowly escaped lynching in the same Ganuwar Kuka village of Hadejia local government.',
        source: "https://www.channelstv.com/2022/09/22/mob-attack-journalist-covering-jigawa-flooding/"
    },
    {
        id: 109,
        title: "NBA Coach Udoka Faces Disciplinary Action For Relationship With Colleague",
        author: "Oluwatukesi Oritsetsemaye",
        time: "September 22, 2022",
        image: "https://www.channelstv.com/wp-content/uploads/2022/09/Ime-Udoka-1.jpg",
        description: "The coach of Bolton Celtics Ime Udoka is currently facing disciplinary action for his involvement in a consensual, intimate relationship with a woman who is a member of staff of the Boston Celtics.",
        body: 'The act is expected to include a significant suspension as the Head Coach of the Boston Celtics. According to ESPN, their sources revealed this information to them on Wednesday. “The relationship was considered a violation of the organization’s guidelines, and a decision on the length of that suspension is expected to come as soon as Thursday” “While no final decision has been made, internal discussions have included scenarios that would keep Udoka out for the entirety of the 2022 - 23 season,” sources said.Ime Udoka who is a Nigerian-American professional basketball coach and a former basketball player for the Nigerian National team is engaged to the multiple award-winning actress Nia Long, they have one child together. “It isn’t believed that Udoka’s job is in jeopardy, Joe Mazzulla would likely be in serious consideration for an interim role,”  sources told ESPN.Udoka replaced Brad Stevens as the Coach of the Celtics in June 2021, he also became the first rookie coach to win multiple Games in his first post-season according to ESPN Stats & Information research. A former D’Tigers forward, Ime Udoka, oversaw Boston Celtics’ qualification to the NBA finals for the first time in 12 years in a spectacular fashion.He is the 18th head coach in the Celtics franchise’s history and the first Nigerian head coach in the history of the NBA.',
        source: "https://www.channelstv.com/2022/09/22/nba-coach-ime-udoka-faces-disciplinary-action-for-relationship-with-female-celtics-staff/"
    },
    {
        id: 1010,
        title: "US Sanctions Iran Morality Police After Woman’s Death",
        author: "Channels Television ",
        time: "September 22, 2022",
        image: "https://www.channelstv.com/wp-content/uploads/2022/09/Mahsa-Amini.jpg",
        description: "The United States placed Iran’s morality police on its sanctions blacklist Thursday following the death in custody of Mahsa Amini, a 22-year-old arrested for allegedly wearing her hijab headscarf improperly.",
        body: 'The US Treasury said the morality police were “responsible” for Amini’s death, which has sparked an outpouring of popular anger, as it announced the sanctions “for abuse and violence against Iranian women and the violation of the rights of peaceful Iranian protestors.” The sanctions move was taken as violent protests erupted across Iran following the death last week of Iranian- Kurdish Amini, who had been arrested by the public morality unit of the national police. “Mahsa Amini was a courageous woman whose death in morality police custody was yet another act of brutality by the Iranian regime’s security forces against its own people,” said Secretary of the Treasury Janet Yellen. “We condemn this unconscionable act in the strongest terms and call on the Iranian government to end its violence against women and its ongoing violent crackdown on free expression and assembly,” Yellen said in a statement.According to an official count, at least 17 people have died in unrest following Amini’s death as women burned their headscarves and protesters denounced the government leadership and restrictions on women. The Oslo- based non - government group Iran Human Rights said at least 31 civilians had been killed in six nights of violence. The Treasury also placed sanctions on Mohammad Rostami Cheshmeh Gachi, the head of the morality police, Haj Ahmad Mirzaei, the head of the morality police’s Tehran division, and five other senior security officials involved in the repressions of protestors. It said Rostami had announced earlier this year that women would be punished for refusing to wear a hijab. “The Iranian government needs to end its systemic persecution of women and allow peaceful protest,” said US Secretary of State Antony Blinken. “The United States will continue to voice our support for human rights in Iran and hold those who violate them to account,” he said in a statement. Treasury sanctions aim to freeze any assets those designated might have under US jurisdiction and forbid any American individuals or companies — including international banks with US operations — from doing business with them, effectively limiting their access to global financial networks.',
        source: "https://www.channelstv.com/2022/09/22/us-sanctions-iran-morality-police-after-womans-death/"
    },
    {
        id: 1011,
        title: "Amanpour Says Iran President Interview Scrapped Over Headscarf Demand",
        author: "Channels Television",
        time: "September 22, 2022",
        image: "https://www.channelstv.com/wp-content/uploads/2022/09/Veteran-journalist-Christiane-Amanpour-cnn.jpg",
        description: "Veteran journalist Christiane Amanpour said Thursday that an interview with Iranian President Ebrahim Raisi was scrapped after he insisted she wear a headscarf, the focus of major protests in the cleric-run state.",
        body: 'Amanpour, the chief international anchor of CNN who also has a show on US public broadcaster PBS, said she was ready for the interview Wednesday on the sidelines of the UN General Assembly when an aide insisted she cover her hair. “I politely declined.We are in New York, where there is no law or tradition regarding headscarves,” Amanpour, who was born in Britain to an Iranian father, wrote on Twitter. “I pointed out that no previous Iranian president has required this when I have interviewed them outside Iran,” she said. “I said that I couldn’t agree to this unprecedented and unexpected condition.” She posted a picture of herself — without a headscarf — sitting in front of an empty chair where Raisi would have been. An aide to Raisi, a hardline cleric, told Amanpour that he was insisting on a headscarf because of “the situation in Iran,” she said. Iran has been swept by nearly a week of protests since the death of 22 - year - old Mahsa Amini, who died after being arrested by morality police that enforce the clerics’ rules on how women dress. A non - governmental group said that at least 31 Iranian civilians have been killed in the crackdown on the protests, in which women have been seen burning headscarves.',
        source: "https://www.channelstv.com/2022/09/22/amanpour-says-iran-president-interview-scrapped-over-headscarf-demand/"
    },
    {
        id: 1012,
        title: "Two Killed As 6.9-Magnitude Earthquake Shakes Mexico",
        author: "Channels Television ",
        time: "September 22, 2022",
        image: "https://www.channelstv.com/wp-content/uploads/2021/11/mexico-flag.jpg",
        description: "A strong earthquake jolted Mexico on Thursday, leaving two people dead as residents rushed out into the streets of the capital in the middle of the night days after another powerful tremor.",
        body: 'A woman died in Mexico City after falling down some stairs and hitting her head when the quake triggered early warning alarms, while the second victim suffered a heart attack, authorities said. The epicenter of the 6.9-magnitude earthquake was near the Pacific coast, 84 kilometers(52 miles) south of Coalcoman in the western state of Michoacan, the national seismological agency reported. The US Geological Survey(USGS) estimated the magnitude at 6.8. It was the strongest of more than 1, 200 aftershocks from a magnitude 7.7 quake that struck the same area on Monday, the national seismological agency said. That tremor left two people dead in western Mexico, damaged several thousand buildings and sparked panic more than 400 kilometers away in Mexico City. The latest quake again triggered alarms in the capital shortly after 1: 00 am(0600 GMT) and caused buildings to shake and sway. Many people quickly evacuated their homes when the alarms sounded, some still dressed in pajamas and carrying their pet dogs. “We had a 6.9 magnitude aftershock with an epicenter in Coalcoman,” President Andres Manuel Lopez Obrador said on Twitter. “It was felt in Michoacan(and the other states of) Colima, Jalisco, Guerrero and Mexico City.So far there are no reports of damage,” he added. Mexico City Mayor Claudia Sheinbaum said official helicopters had flown over the city and that there were no initial reports of destruction. “So far there is no damage in the city after the earthquake,” she tweeted. The quake hit at a depth of 12 kilometers, according to the national seismological agency, while the USGS estimated the depth at 24 kilometers, located about 410 kilometers from Mexico City.',
        source: "https://www.channelstv.com/2022/09/22/two-killed-as-6-9-magnitude-earthquake-shakes-mexico/"
    },
    {
        id: 1013,
        title: "Manchester United Report £115.5m Loss For 2021/22 Season",
        author: "Channels Television",
        time: "September 22, 2022",
        image: "https://www.channelstv.com/wp-content/uploads/2022/05/Untitled-1-Recovered-Recovered-5.png",
        description: "Manchester United on Thursday announced a net loss of £115.5 million ($130.4 million, 132.2 million euros) for the 2021/22 season even though revenues rose to £583 million as coronavirus restrictions eased.",
        body: 'The financial year to June 30, 2022 also brought a 22 per cent rise in debt and a 19 per cent increase in wages. The 20-time English champions’ net debt increased from £419.5 million in 2021 to £514.9 million. United attributed the rise in debt mainly to the fall of the pound which increased the value of US dollar borrowings. Among other large items were dividends of £33.6 million to shareholders and the £24.7 million compensation package for former manager Ole Gunnar Solskjaer, sacked in November 2021. The biggest contributor to United’s spiralling costs was the increase in wages to £384.2 million. The return of Cristiano Ronaldo to Old Trafford, allied to summer signings of Raphael Varane and Jadon Sancho had United fans dreaming of a Premier League title challenge a year ago. Instead, they finished sixth, with their lowest points total of the Premier League era. The failure to qualify for the Champions League will hit United’s finances for this season. The club still heavily backed new manager Erik ten Hag in the summer, spending over £200 million on Antony, Casemiro, Lisandro Martinez and Tyrell Malacia. “Our club’s core mission is to win football matches and entertain our fans,” said United CEO Richard Arnold. “Since our last earnings report, we have strengthened our men’s first team squad, completed a successful summer tour, and established a foundation to build from in the early stages of the 2022 / 23 season under our new manager.” After a disastrous start to Ten Hag’s reign with defeats to Brighton and Brentford, United have won their last four Premier League games to climb to fifth in the table, six points behind early season leaders Arsenal but with a game in hand.',
        source: "https://www.channelstv.com/2022/09/22/manchester-united-report-115-5m-loss-for-2021-22-season/"
    },
    {
        id: 1014,
        title: "Rafael Nadal Looks Forward To ‘Unforgettable’ Doubles With Roger Federer",
        author: "Channels Television",
        time: "September 22, 2022",
        image: "https://www.channelstv.com/wp-content/uploads/2022/09/Roger-Federer-will-team-up-with-rival-Rafael-Nadal.jpg",
        description: "Roger Federer will team up with long-time rival Rafael Nadal for the final match of his glittering career, Laver Cup organisers announced on Thursday.",
        body: 'The 20-time Grand Slam champion will play doubles with the Spaniard, who has won 22 majors, at the O2 arena in London on Friday. Federer, whose most recent competitive match was a loss to Hubert Hurkacz in last year’s Wimbledon quarter- finals, has been struggling with a knee problem and will not play singles in London. The Laver Cup is a team competition that pits Team Europe against Team World. The six - strong European team, captained by Bjorn Borg, also includes 21 - time major winner Novak Djokovic and three - time major winner Andy Murray. Their opponents, Team World, skippered by John McEnroe, include Taylor Fritz, Felix Auger - Aliassime and Diego Schwartzman. Federer, 41, announced last week he intended to retire after the three - day Laver Cup. He said on Wednesday that finishing his career by teaming up with Nadal would be his dream scenario. Federer said he and Nadal, 36, had always maintained respect for each other even as they vied for the biggest trophies in the sport. “For us as well to go through a career that we both have had and to come out on the other side and being able to have a nice relationship I think is maybe a great message as well to not just tennis but sports and maybe even beyond,” he said. Italian Matteo Berrettini, the first alternate for Europe, will take Federer’s place over the weekend.',
        source: "https://www.channelstv.com/2022/09/22/rafael-nadal-looks-forward-to-unforgettable-doubles-with-roger-federer/"
    },
    {
        id: 1015,
        title: "Raducanu Surges Into Quarter-Finals At Korea Open",
        author: "Channels Television",
        time: "September 22, 2022",
        image: "https://www.channelstv.com/wp-content/uploads/2022/09/Emma-Raducanu.jpg",
        description: "Former US Open champion Emma Raducanu reached the quarter-finals of the Korea Open on Thursday, beating 396th-ranked Yanina Wickmayer of Belgium in straight sets.",
        body: 'Raducanu, who crashed out of the US Open in the first round last month, overcame a sluggish start and a late wobble to win 6-3, 7-5 in Seoul. The 19-year - old Briton, the sixth seed, will face third seed Magda Linette of Poland next. Raducanu reached a career- high 10th in the world in July, but is now 77th, having failed to build on her shock success at Flushing Meadows last year. Wickmayer held her own initially, exchanging breaks to 3 - 3, before the Briton picked up the pace to take the first set. Raducanu carried that momentum into the second set and was leading 4 - 1, only for Wickmayer to fight back to 4 - 4. Raducanu eventually pulled through, breaking Wickmayer’s serve on the way to clinching the set and match.',
        source: "https://www.channelstv.com/2022/09/22/raducanu-surges-into-quarter-finals-at-korea-open/"
    },
    {
        id: 1016,
        title: "Chelsea Sack Commercial Director Over ‘Inappropriate Messages’",
        author: "Channels Television",
        time: "September 22, 2022",
        image: "https://www.channelstv.com/wp-content/uploads/2022/05/Chelsea.jpg",
        description: "Chelsea have sacked recently appointed commercial director Damian Willoughby over “inappropriate messages” he sent before he joined the Premier League club.",
        body: 'It is understood the messages were sent to Catalina Kim, a football agent who is the founder and chief executive of C&P Sports Group. C& P was involved in a bid by British property tycoon Nick Candy to buy Chelsea from Roman Abramovich before American Todd Boehly’s consortium completed a takeover in May. Willoughby was appointed as commercial director earlier this month, returning to the club he had previously worked at from 2007 to 2010. “Chelsea Football Club confirms that it has terminated commercial director Damian Willoughby’s employment with immediate effect,” said a club spokesman. “Evidence of inappropriate messages sent by Mr Willoughby, prior to his appointment at Chelsea FC earlier this month, has recently been provided to and investigated by the club. “While they were sent prior to his employment at the club, such behaviour runs absolutely counter to the workplace environment and corporate culture being established by the club’s new ownership.”',
        source: "https://www.channelstv.com/2022/09/22/chelsea-sack-commercial-director-over-inappropriate-messages/"
    },
    {
        id: 1017,
        title: "US Jury Orders Meta To Pay $174.5mn For Violating Patents",
        author: "Channels Television",
        time: "September 22, 2022",
        image: "https://www.channelstv.com/wp-content/uploads/2022/06/Facebook-parent-company-Meta.jpg",
        description: "A US jury on Wednesday ordered Meta to pay $174.5 million for violating live-streaming patents developed by a US Army veteran seeking to fix shortcomings in battlefield communications.",
        body: 'A trial in Texas federal court ended with jurors deciding that “live” features at Facebook and Instagram used technology patented by Voxer, a company co-founded by Tom Katis, legal documents showed. “We believe the evidence at trial demonstrated that Meta did not infringe Voxer’s patents,” a company spokesperson said in response to an AFP inquiry. “We intend to seek further relief, including filing an appeal.” Katis had reenlisted in the army after the September 11, 2001 attacks in the United States and served as a Special Forces communications sergeant in Afghanistan, court filings said. When his combat unit was ambushed in Kunar province, he felt that the systems for coordinating reinforcements, medical evacuations and more “were ill-suited for time-sensitive communications with multiple groups in a highly disruptive environment,” the complaint said. “Mr. Katis and his team began developing communications solutions in 2006 to remedy these shortcomings,” his lawyers said. “The new technologies enabled transmission of voice and video communications with the immediacy of live communication and the reliability and convenience of messaging.” Facebook approached San Francisco-based Voxer about potential collaboration after it launched a Walkie Talkie app in 2011, but no agreement was reached, according to legal documents. Instead, the lawsuit argued, Facebook went on to launch Facebook Live and Instagram Live, incorporating Voxer technology into the features.',
        source: "https://www.channelstv.com/2022/09/22/us-jury-orders-meta-to-pay-174-5mn-for-violating-patents/"
    },
    {
        id: 1018,
        title: "PIA To Unlock Investments In Nigeria’s Oil And Gas Sector – Sylva",
        author: "Channels Television",
        time: "September 22, 2022",
        image: "https://www.channelstv.com/wp-content/uploads/2021/08/Timipre-Sylva2.jpg",
        description: "The Minister of State Petroleum Resources, Chief Timipre Sylva, has said that the desire to surmount the challenges bedeviling the oil and gas sector led to the enactment of the Petroleum Industry Act (PIA).",
        body: 'Speaking at the Nigeria International Economic Partnership Forum, in New York, on Wednesday, with the theme: “Nigeria’s Oil and Gas Sector: Reforms, Results and the Road Ahead”, Sylva said the desire of the President Muhammadu Buhari’s government to inject life into the sector hitherto characterized by fiscal and operational challenges led to making proactive reforms in the sector a priority. The minister said the enactment of the Petroleum Industry Act(PIA) on August 16, 2022 was a “watershed moment for the nation, the industry and all stakeholders alike, signaling the beginning of a more conducive environment for investment, output, industrial and national growth, while also addressing legitimate grievances of resource host- communities most impacted by resource extraction operations”.Sylva said the “PIA 2021, at full implementation, will create massive investment opportunities, improve transparency, attract investors, and reposition the Nigerian Oil and Gas industry for sustainable growth,” urging investors “to capitalize on the sustainable incentives provided by the PIA 2021 to invest in the oil and gas industry in Nigeria” with no future regret. The minister told the gathering that the “PIA 2021 has established a legal, governance, regulatory, and fiscal framework for the petroleum industry, host community development, and associated matters” adding that “it provides fiscal certainty, improves regulations and incentives for investment, including up to ten- year tax vacations, while guaranteeing better take for both government and private investors, thereby balancing rewards with risk”. The minister who said the PIA has set the foundation for a sustainable growth in the sector with the establishment of the Nigerian National Petroleum Company Limited(NNPCL), Nigerian Midstream and Downstream Petroleum Regulatory Authority(NMDPRA) and Nigerian Upstream Petroleum Regulatory Commission(NUPRC) reassured the international investors of government’s commitment in the sector. “This administration remains committed to ensure a full implementation of these carefully conceived reforms to foster efficiency and attract investments and development of supporting infrastructure along the oil and gas value chain as embedded in our policy aspirations for the sector.',
        source: "https://www.channelstv.com/2022/09/22/pia-to-unlock-investments-in-nigerias-oil-and-gas-sector-sylva/"
    },
    {
        id: 1019,
        title: "My Journey Is Not Over Yet, Ronaldo Dismisses Retirement",
        author: "Channels Television",
        time: "September 21, 2022",
        image: "https://www.channelstv.com/wp-content/uploads/2022/09/Ronaldo.jpg",
        description: "Cristiano Ronaldo has set his sights on reaching Euro 2024 and Portugal and Manchester United forward says he has no plans to retire any time soon.",
        body: '“My journey is not over yet, you’re going to have to put up with ‘Cris’ for a while longer,” said Ronaldo on Tuesday, after receiving a trophy at the Portuguese football federation’s (FPF) Quinas de Ouro awards in Lisbon for being the top national team goalscorer of all time.“I want to be part of the World Cup and the Euros … I feel very motivated. My ambition is great,” the 37-year-old said. Ronaldo has scored 117 goals in 189 Portugal appearances and is expecting to play in his 10th major international tournament for his country at Qatar 2022. The forward’s brace against the Republic of Ireland in September 2021 allowed him to overtake Iranian great Ali Daei’s haul of 109 goals as the record international scorer. Ronaldo eventually stayed at Manchester United this summer despite speculation he would switch clubs, and despite being benched for Premier League matches he scored in the team’s last outing at Moldovan minnows FC Sheriff in the Europa League.',
        source: "https://www.channelstv.com/2022/09/21/my-journey-is-not-over-yet-ronaldo-dismisses-retirement/"
    },
    {
        id: 1020,
        title: "Euro 2024: Russia Banned From Qualifying Draw",
        author: "Channels Television",
        time: "September 21, 2022",
        image: "https://www.channelstv.com/wp-content/uploads/2018/06/football.jpg",
        description: "Russia will not take part in the draw for qualifying for Euro 2024, UEFA and the country’s football federation confirmed on Tuesday.",
        body: 'The Russian national team and Russian clubs were banned from international competitions earlier this year by UEFA following the invasion of Ukraine.“All Russian teams are currently suspended following the decision of the UEFA Executive Committee of 28 February 2022 which has further been confirmed by the Court of Arbitration for Sport on 15 July 2022,” European football’s governing body said in a statement. “Russia is therefore not included in the UEFA European Football Championship 2022 - 24 qualifying draw.” Russia saw an appeal against the ban rejected by CAS in July. “The Union is currently awaiting the full text of the CAS decision, following the study of which a decision will be made on further steps,” the Russian Football Union said. Russia were also banned from the upcoming World Cup in Qatar by FIFA. The team had originally qualified for the European qualifying playoffs. The Russian women’s side were also kicked out of this year’s Euro in England, with their place taken by Portugal. The 2024 European Championship will be hosted by Germany, with the qualifying draw set for October 9 in Frankfurt. Germany’s interior minister has also asked for Belarus to be banned from the tournament due to the country’s backing of Russia.',
        source: "https://www.channelstv.com/2022/09/21/euro-2024-russia-banned-from-qualifying-draw/"
    },
    {
        id: 1021,
        title: "Pilot In Crash That Killed Footballer Sala Said Plane Was ‘Dodgy’ – Report",
        author: "Channels Television",
        time: "September 21, 2022",
        image: "https://www.channelstv.com/wp-content/uploads/2019/02/sala-1.jpg",
        description: "The pilot flying the plane that came down in the English Channel, killing Argentinian footballer Emiliano Sala, previously complained that the aircraft was “dodgy”, according to audio obtained by the BBC.",
        body: 'Sala, 28, and pilot David Ibbotson, 59, died when the single-engined Piper Malibu plane they were travelling in came down en route from Nantes, northwest France, to Cardiff in 2019. The footballer inhaled toxic levels of carbon monoxide from the aircraft’s faulty exhaust system during the unlicensed flight, a coroner’s inquest ruled in March.In a phone message to another pilot, Ibbotson said “they’ve entrusted me to pick him (Sala) up in a dodgy Mirage,” according to the BBC. “Normally I’d have my life jacket in between the seats, tomorrow we’re wearing the life jacket, that’s for sure.” The forward had signed for Cardiff City, who were then in the Premier League, for a club record £15 million(17 million euros, $17 million) from Nantes. Ibbotson said in the message that he had heard a bang when previously flying the plane, and that its left brake pedal wasn’t working. “This aircraft has got to go back in the hangar,” he told his friend. The footballer also voiced his fears in a voice note sent to friends, telling them, “man, I’m scared” and that the plane “looks like it’s falling apart”. David Henderson, 67, who organised the flight, was sentenced after a criminal trial last November to 18 months in prison for hiring a pilot he knew to be unqualified and for carrying a passenger without valid authorisation. The Court of Arbitration for Sport in August dismissed an appeal by Cardiff against having to pay Nantes six million euros, the first installment of Sala’s transfer fee.',
        source: "https://www.channelstv.com/2022/09/21/pilot-in-crash-that-killed-footballer-sala-said-plane-was-dodgy-report/"
    },
    {
        id: 1022,
        title: "Gates Foundation Honours Four Leaders With 2022 Goalkeepers Global Awards",
        author: "Channels Television ",
        time: "September 21, 2022",
        image: "https://www.channelstv.com/wp-content/uploads/2016/07/Bill-Gates.jpg",
        description: "The Bill & Melinda Gates Foundation on Tuesday announced the winners of its annual Goalkeepers Global Goals Awards",
        body: 'In a statement, the Foundation recognized Radhika Batra of India, Zahra Joya of Afghanistan, Vanessa Nakate of Uganda, and Ursula von der Leyen of Germany for their extraordinary work towards achieving the United Nations Sustainable Development Goals in their communities and around the world. Radhika Batra, co- founder of the nonprofit organization Every Infant Matters, which provides last - mile health solutions to disadvantaged children in India. Zahra Joya, a journalist from Afghanistan who founded and self - funded Rukhshana Media, an online news agency focused exclusively on covering issues that affect the women of Afghanistan. Vanessa Nakate, a climate justice activist from Uganda and founder of the Africa - based Rise Up Movement and the Green Schools Project. Ursula von der Leyen, president of the European Commission. The winners were announced at the Goalkeepers Awards Ceremony, which was attended by global leaders, influencers, and changemakers, and hosted by Tumelo Mothotoane, senior anchor at South African news broadcaster eNCA Award presenters included Malala Fund co - founder and Nobel Peace Prize laureate, Malala Yousafzai; and entertainer and founder of Unicorn Island, Lilly Singh. “While the world is far from being on track to reach the Global Goals by 2030, there is still cause for optimism.We’ve seen how human ingenuity and innovation can lead to game - changing breakthroughs and progress toward our shared goals, and that’s exactly what we see in this year’s Goalkeepers Global Goals Award winners,” said Blessing Omakwu, head of Goalkeepers. “Each show us how women are leading the way in coming up with the innovative solutions to move the numbers in the right direction, so that more people can lead healthy and productive lives,” Omakwu added. ',
        source: "https://www.channelstv.com/2022/09/21/gates-foundation-honours-four-leaders-with-2022-goalkeepers-global-awards/"
    },
    {
        id: 1023,
        title: "National Mourning Ends In Britain After Queen’s Funeral",
        author: "Channels Television",
        time: "September 20, 2022",
        image: "https://www.channelstv.com/wp-content/uploads/2022/09/full-mast.jpg",
        description: "Flags on government buildings returned to full mast and an epic clean-up operation was underway on Tuesday as British public life resumed after the state funeral of Queen Elizabeth II, although the royal family remains in mourning for another week.",
        body: 'Around a quarter of a million people queued round the clock to view the queen’s coffin as it lay in state in the days leading up to the funeral, the UK government said. Liz Truss, appointed prime minister by the queen just two days before she died on September 8, flew to the UN General Assembly hours after delivering a biblical reading at the lavish funeral. En route to New York, Truss praised the “huge outpouring of love and affection” shown towards the late monarch, as well as the “huge amount of warmth towards” her successor, King Charles III. Charles, 73, and his family will remain in mourning for another seven days. That means no official engagements after he spent an exhausting week touring his new kingdom and attending to the ornate pageantry of a role that he has spent a lifetime preparing to take on. The royal Twitter account published a picture of the queen hiking in 1971 at her Scottish retreat of Balmoral, where she died at the age of 96 as Britain’s longest- reigning monarch. The photograph was accompanied with the words: “May flights of Angels sing thee to thy rest.In loving memory of Her Majesty The Queen.” The quotation is from the tragic conclusion of Shakespeare’s play “Hamlet” and was said by Charles in his first national broadcast as king the day after his mother passed away. ',
        source: "https://www.channelstv.com/2022/09/20/national-mourning-ends-in-britain-after-queens-funeral/"
    },
    {
        id: 1024,
        title: "Recovering Barca Predict 1.3 Billion Euro Revenue",
        author: "Channels Television",
        time: "September 20, 2022",
        image: "https://www.channelstv.com/wp-content/uploads/2022/04/untitled-Recovered-5.png",
        description: "Barcelona have forecast revenue of 1.255 billion euros ($1.254 billion) for the 2022-23 season, with a predicted profit of 274 million euros.",
        body: 'The Spanish side have been under great economic stress in recent years but gained financial leverage this summer with a string of operations which allowed them to strengthen the team. Barca signed Bayern Munich striker Robert Lewandowski, Sevilla defender Jules Kounde, Leeds United winger Raphinha and various other players on free transfers. They were able to do this after selling 25 percent of their television rights to investment firm Sixth Street for the next 25 years, raising over 500 million euros. Barcelona also sold 24.5 percent of their Barca Studios production company to fan token firm Socios.com and the same amount again to Orpheus Media, for around 100 million euros each.These deals, plus the return of supporters in droves after low attendances last season, mean their expected income for next season has risen from last year’s revenue of 1.017 billion euros and a profit of 98 million euros. In the 2020-21 season Barcelona posted losses of 481 million euros and blamed them for not being able to renew their all- time record scorer Lionel Messi’s contract, leading him to sign for Paris Saint - Germain on a free transfer. The club spent heavily for several years, bringing in Brazilian midfielder Philippe Coutinho from Liverpool in a club record deal worth up to 160 million euros in 2018, before later selling him to Aston Villa for around 20 million euros, among other ill - fated operations. Along with income being severely hit by the pandemic, it drove the team to the brink of crisis, with president Joan Laporta saying when he took over in March 2021 the team was “dead”. “We restructured the debt, we controlled the bills, we reduced the sporting salary a bit but not enough yet, we found new income and sponsors,” Laporta told club members in June. “We went from being dead to being in intensive care.”',
        source: "https://www.channelstv.com/2022/09/20/recovering-barca-predict-1-3-billion-euro-revenue/"
    },
    {
        id: 1025,
        title: "Russia Banned From Euro 2024 Qualifying Draw",
        author: "Channels Television",
        time: "September 20, 2022",
        image: "https://www.channelstv.com/wp-content/uploads/2020/04/uefa.png",
        description: "Russia will not take part in the draw for qualifying for Euro 2024, UEFA and the country’s football federation confirmed on Tuesday.",
        body: 'The Russian national team and Russian clubs were banned from international competitions earlier this year by UEFA following the invasion of Ukraine. “All Russian teams are currently suspended following the decision of the UEFA Executive Committee of 28 February 2022 which has further been confirmed by the Court of Arbitration for Sport on 15 July 2022,” European football’s governing body said in a statement. “Russia is therefore not included in the UEFA European Football Championship 2022 - 24 qualifying draw.” Russia saw an appeal against the ban rejected by CAS in July. “The Union is currently awaiting for the full text of the CAS decision, following the study of which a decision will be made on further steps,” the Russian Football Union said. Russia were also banned from the upcoming World Cup in Qatar by FIFA. The team had originally qualified for the European qualifying play - offs. The Russian women’s side were also kicked out of this year’s Euro in England, with their place taken by Portugal. The 2024 European Championship will be hosted by Germany, with the qualifying draw set for October 9 in Frankfurt. Germany’s interior minister has also asked for Belarus to be banned from the tournament due to the country’s backing of Russia.',
        source: ""
    },
    {
        id: 1026,
        title: "Grealish And Haaland Destroy Wolves As Man City Go Top",
        author: "Channels Television",
        time: "September 17, 2022",
        image: "https://www.channelstv.com/wp-content/uploads/2022/09/halaand.jpg",
        description: "Jack Grealish scored his first goal this season and Erling Haaland extended his record-breaking hot-streak as Manchester City powered to a 3-0 win over 10-man Wolves on Saturday.",
        body: 'Pep Guardiola’s side needed just 56 seconds to take the lead at Molineux as Grealish finally enjoyed a day to remember after a difficult time since joining City from Aston Villa last year. Haaland doubled City’s advantage with his 14th goal in 10 games in all competitions following a £51 million($58 million) move from Borussia Dortmund that already appears a bargain. Wolves lost any chance of a fightback when Nathan Collins was sent off for an ugly stomach- high foul on Grealish in the first half. Phil Foden capped City’s stroll in the midlands sunshine as the Premier League champions moved to the top of the table. Unbeaten City are two points clear of second - placed Arsenal, who would regain pole position if they win at Brentford on Sunday. “The game started really well for us with the two goals and the red card.After the Champions League to come here at 12: 30 with the quality they have, it was an incredible victory,” Guardiola said. Guardiola said this week that the “exceptional” Haaland was the “perfect” person to manage because his personality ensured he always remains hungry to improve. Even Guardiola may run out of superlatives to describe the 22 - year - old Norwegian if he continues this astonishing run. Haaland was named Premier League Player of the Month for August after his blistering start to the season and he is already making his case for the September award. He has netted in seven successive games for City and is the first player to score in their first four Premier League away appearances. Showing their hunger to win the title for a fifth time in six seasons, City are unbeaten in a club record 22 away league matches since losing at Tottenham in their opening game last season.',
        source: "https://www.channelstv.com/2022/09/17/grealish-and-haaland-destroy-wolves-as-man-city-go-top/"
    },
    {
        id: 1027,
        title: "Google Loses Appeal Against Record EU Antitrust Fine",
        author: "Channels Television",
        time: "September 14, 2022",
        image: "https://www.channelstv.com/wp-content/uploads/2022/01/google3.jpg",
        description: "The European Union’s second-highest court on Wednesday overwhelmingly upheld the EU’s record fine against Google over its Android operating system for mobile phones, slightly reducing the fee for technical reasons.",
        body: 'In a statement, the EU’s General court said it “largely confirms the commission’s decision that Google imposed unlawful restrictions on manufacturers of Android mobile devices” in order to benefit its search engine. The court, however, said the fine should be slightly reduced to 4.125 billion euros($4.1 billion), instead of the 4.3 billion euros decided by the commission in 2018 after reviewing the duration of the infringement. The levy remains the EU’s biggest ever despite Google’s arguments that the commission’s case was unfounded and falsely relied on accusations it imposed its search engine and Chrome browser on Android phones. The company also pushed the case that the EU was unfairly blind to the strength of Apple, which imposes or gives clear preference to its own services such as Safari on iPhones. Google insisted that downloading rival apps was only a click away and that customers were in no way tied to Google products on Android. The EU and complainants responded that Google used contracts with phone makers in the early days of Android to stifle rivals. “This shows the European Commission got it right,” said Thomas Vinje, a lawyer representing FairSearch, whose original complaint launched the case in 2013. “Google can no longer impose its will on phone makers.Now they may open their devices to competition in search and other services, allowing consumers to benefit from increased choice,” he added. The decision by the General Court is not necessarily the end of the story.Both sides can turn to the EU’s highest court, the European Court of Justice, for a final say on the fine, which was the equivalent of $5 billion when levied.',
        source: "https://www.channelstv.com/2022/09/14/google-loses-appeal-against-record-eu-antitrust-fine/"
    },
    {
        id: 1028,
        title: "Theranos Founder Elizabeth Holmes Seeks New Fraud Trial",
        author: "Channels Television",
        time: "September 7, 2022",
        image: "https://www.channelstv.com/wp-content/uploads/2022/09/Elizabeth-Holmes.jpg",
        description: 'Convicted Theranos founder Elizabeth Holmes on Monday asked for a new trial, saying a star prosecution witness showed up at her home saying he felt he had “done something wrong.”',
        body: 'Holmes is scheduled to be sentenced in October after a jury early this year found her guilty of defrauding investors in her blood-testing startup Theranos. Holmes is a rare example of a tech exec being brought to book over a company flaming out, in a sector littered with the carcasses of money- losing businesses that once promised untold riches. Her case shone a spotlight on the blurred line between the hustle that characterizes the industry and outright criminal dishonesty. But attorneys for Holmes said that former Theranos lab manager Adam Rosendorff, who was part of the prosecution’s case, arrived unannounced at her California home in August looking disheveled and saying he needed to speak with her. “He said he feels guilty, it seemed like he was hurting,” Holmes’s partner William Evans said of Rosendorff in an exhibit with the court. “He said when he was called as a witness he tried to answer the questions honestly but that the prosecutors tried to make everybody look bad(in the company).” Evans said he turned Rosendorff away from the home he shares with Holmes and their young son, telling Rosendorff that Holmes could not speak with him. “He said he thought it would be healing for both himself and Elizabeth to talk,” said Evans.” – Different verdict ?  Evans recounted Rosendorff saying that both he and Holmes were just starting out in their careers when they worked together at Theranos, and that “everyone was working so hard to do something good and meaningful.” Holmes had vowed to revolutionize health diagnostics with self - service machines that could run an array of tests on just a few drops of blood, a vision that drew high - profile backers and made her a billionaire on paper by the age of 30. She was hailed as the next tech visionary on magazine covers and collected mountains of investors’ cash, but it all collapsed after Wall Street Journal reporting revealed the machines did not work as promised. Jurors found her guilty of four counts of tricking investors. But the jury also acquitted her on four charges and could not reach a verdict on three others. The 38 - year - old now faces the possibility of decades behind bars.Attorneys for Holmes argued that Rosendorff was a star witness for prosecutors, and that his statements put the guilty verdict in doubt.',
        source: "https://www.channelstv.com/2022/09/07/theranos-founder-elizabeth-holmes-seeks-new-fraud-trial/"
    },
    {
        id: 1029,
        title: "Brazil Fines Apple $2.4m, Prohibits Sale Of iPhone Without Charger",
        author: "Channels Television",
        time: "September 6, 2022",
        image: "https://www.channelstv.com/wp-content/uploads/2021/10/apple.jpg",
        description: 'Apple has been barred from selling iPhones without a charger in Brazil and fined more than $2 million over the issue, the government said Tuesday, after accusing the US tech giant of “discriminatory practices.”',
        body: 'In an official notice, Brazilian authorities ordered “the immediate suspension of the distribution of iPhone brand smartphones, regardless of model or generation, that are not accompanied by a battery charger.” The Ministry of Justice and Public Security ordered the California company to pay a fine of 12.28 million reais(nearly $2.4 million). The measure from the Department of Consumer Protection and Defense effectively prohibits the sale of all iPhone 12 and 13 models. Apple has been under investigation in Brazil since December for “the sale of an incomplete product,” “discrimination against the consumer” and “the transfer of responsibility to third parties” by offering iPhone 12s and newer versions without chargers for power outlets, according to an official statement. The company has faced fines from Brazilian state agencies before, but “did not take any measures to minimize the harm and until now continued to sell the cellular devices without chargers,” the statement said. According to Brazilian authorities, Apple alleges that the decision to exclude chargers from iPhone sales comes from an “environmental commitment.” But the ministry determined “there is no effective demonstration of environmental protection on Brazilian soil as a consequence” of Apple’s policy, and accused the company of “deliberate discriminatory practices against consumers.” “There is no justification for an operation which, in aiming to reduce carbon emissions, leads to the introduction into the consumer market of a product whose use depends on the acquisition of another(product) which is also marketed by the company,” the official notice added.',
        source: "https://www.channelstv.com/2022/09/06/brazil-fines-apple-2-4m-prohibits-sale-of-iphone-without-charger/"
    },
    {
        id: 1030,
        title: "Twitter Says It Is Actively Testing Edit Button",
        author: "Channels Television",
        time: "September 1, 2022",
        image: "https://www.channelstv.com/wp-content/uploads/2022/05/Twitter.jpg",
        description: "Twitter said Thursday it has begun actively testing an edit button, after months of publicly discussing such a tweak.",
        body: '“Edit Tweet is a feature that lets people make changes to their Tweet after it’s been published,” the company said on its blog. “Think of it as a short period of time to do things like fix typos, add missed tags, and more.” Under the revision being studied, users could edit a tweet “a few times” in the 30 minutes after the initial posting, in ways that transparently note the changes to “help protect the integrity of the conversation and create a publicly accessible record of what was said,” the company said.Tesla Chief Executive Elon Musk, who is locked in a lawsuit with Twitter over a potential acquisition of the micro-blogging platform, had backed an edit button shortly before the company said in April it was studying the change. Users of Twitter Blue — the subscription offering now available in the United States, Canada, Australia, and New Zeeland– “receive early access to features and help us test them before they come to Twitter,” the company said. An aim of the tweak is that “Tweeting will feel more approachable and less stressful, Twitter said. “You should be able to participate in the conversation in a way that makes sense to you, and we’ll keep working on ways that make it feel effortless to do just that.” However, a Twitter spokesperson said the test will not necessarily be employed universally on the platform.',
        source: "https://www.channelstv.com/2022/09/01/twitter-says-it-is-actively-testing-edit-button/"
    },

]
